### ISSUE TITLE
problems linking to icu

### ISSUE THREAD

**Issue by amerb** [conda-forge/libxml2-feedstock#50]
Issue:
I'm running into a problem correctly attributing environmental variables:
When I set it to:
export XML2INC="/home/.../anaconda2/envs/supp/include"
I receive the following:
espa_metadata.h:20:27: fatal error: libxml/parser.h: No such file or directory
 #include <libxml/parser.h>

However, when I change it to to:
export XML2INC="/home/../anaconda2/envs/supp/include/libxml2"
I get the following compilation error
/home/.../anaconda2/envs/supp/include/libxml2/libxml/encoding.h:31:26: fatal error: unicode/ucnv.h: No such file or directory
 #include <unicode/ucnv.h>

Am I missing something obvious here?

I'm working with libxml2-2.9.8

<br/>
Environment (<code>conda list</code>):
<details>

```
$ conda list
# Name                    Version                   Build  Channel
bzip2                     1.0.8                h516909a_0    conda-forge
ca-certificates           2019.6.16            hecc5488_0    conda-forge
certifi                   2019.6.16                py27_1    conda-forge
cftime                    1.0.3.4         py27hd352d35_1001    conda-forge
curl                      7.65.3               hf8cf82a_0    conda-forge
gettext                   0.19.8.1          hc5be6a0_1002    conda-forge
hdf4                      4.2.13            h9a582f1_1002    conda-forge
hdf5                      1.10.5          nompi_h3c11f04_1100    conda-forge
icu                       58.2              hf484d3e_1000    conda-forge
idna                      2.8                   py27_1000    conda-forge
jbig                      2.1               h14c3975_2001    conda-forge
jpeg                      9c                h14c3975_1001    conda-forge
krb5                      1.16.3            h05b26f9_1001    conda-forge
libblas                   3.8.0               12_openblas    conda-forge
libcblas                  3.8.0               12_openblas    conda-forge
libcurl                   7.65.3               hda55be3_0    conda-forge
libedit                   3.1.20170329      hf8c457e_1001    conda-forge
libffi                    3.2.1             he1b5a44_1006    conda-forge
libgcc-ng                 7.3.0                hdf63c60_0    conda-forge/label/broken
libgfortran-ng            7.2.0                hdf63c60_3    conda-forge/label/broken
libiconv                  1.15              h516909a_1005    conda-forge
libidn2                   2.1.1                h14c3975_0    conda-forge
liblapack                 3.8.0               12_openblas    conda-forge
libnetcdf                 4.6.2             h056eaf5_1002    conda-forge
libopenblas               0.3.7                h6e990d7_0    conda-forge
libpng                    1.6.37               hed695b0_0    conda-forge
libssh2                   1.8.2                h22169c7_2    conda-forge
libstdcxx-ng              7.3.0                hdf63c60_0    conda-forge/label/broken
libtiff                   4.0.10            h57b8799_1003    conda-forge
libxml2                   2.9.8                h422b904_5    conda-forge
lz4-c                     1.8.3             he1b5a44_1001    conda-forge
ncurses                   6.1               hf484d3e_1002    conda-forge
netcdf4                   1.5.1.2          py27h73a1b54_1    conda-forge
numpy                     1.16.4           py27h95a1406_0    conda-forge
openjpeg                  2.3.1                h58a6597_0    conda-forge
openssl                   1.1.1c               h516909a_0    conda-forge
pip                       19.2.2                   py27_0    conda-forge
python                    2.7.15            h5a48372_1009    conda-forge
readline                  8.0                  hf8c457e_0    conda-forge
setuptools                41.0.1                   py27_0    conda-forge
sqlite                    3.29.0               hcee41ef_0    conda-forge
tk                        8.6.9             hed695b0_1002    conda-forge
wheel                     0.33.4                   py27_0    conda-forge
xz                        5.2.4             h14c3975_1001    conda-forge
zlib                      1.2.11            h516909a_1005    conda-forge
zstd                      1.4.0                h3b9ef0a_0    conda-forge

```
</details>

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>

```
$ conda info

     active environment : supp
    active env location : /home/.../anaconda2/envs/supp
            shell level : 2
       user config file : /home/.../.condarc
 populated config files : /home/.../.condarc
          conda version : 4.7.11
    conda-build version : not installed
         python version : 3.7.4.final.0
       virtual packages :
       base environment : /home/../anaconda2  (writable)
           channel URLs : https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://conda.anaconda.org/conda-forge/label/broken/linux-64
                          https://conda.anaconda.org/conda-forge/label/broken/noarch
                          https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /home/ae42b/anaconda2/pkgs
                          /home/.../.conda/pkgs
       envs directories : /home/.../anaconda2/envs
                          /home/.../.conda/envs
               platform : linux-64
             user-agent : conda/4.7.11 requests/2.22.0 CPython/3.7.4 Linux/2.6.32-754.6.3.el6.x86_64 rhel/6.10 glibc/2.12
                UID:GID : 40046:1060
             netrc file : None
           offline mode : False

```
</details>

**Comment by hmaarrfk** [comment]
i think you are supposed to use pkg-config to get the necessary include directories.

I hope yo ufound a solution to your problem years ago.

I'll close in a few days if we don't hear back.
